### ISSUE TITLE
Difference in results in new version with buttons

### ISSUE THREAD

**Issue by ktrzcinskiwb** [worldbank/simvat#100]
@zross

Thank you so much for adding in this functionality, and it seems to be working as desired _except_ this very strange error I'm getting. 

I am only able to reproduce it under a very specific scenario (one that we are using in our training materials). In this scenario, among some other changes, we want to remove the cashback. One way to do this would be to set the parameters we want and then set the "Cobertura cashback" slider to 0. This replicates the results from the Excel (and also the previous version of the app, before the implementation of the buttons):

https://github.com/zevross/rpkg-worldbank-simvat/assets/164540200/e832c1b4-e0a5-4218-8a18-5ed8f957a69c

Another way to achieve the same thing would be to use the buttons and set the cashback to zero for all the macro-categories:

https://github.com/zevross/rpkg-worldbank-simvat/assets/164540200/cd5f114f-fd35-4d22-9f3b-a890137d06dc

In this case I observe three things: 
1. the cashback for "Recreações culturais e esportivas" does not update along with the others
2. the results come out a bit differentc - aliquodta simulada is 28.4% instead of 28.3%, the 10th decile is off by 0.1 percentage point
3. if I use the cobertura cashback slider _after_ this to set the cashback to 0 it doesn't reproduce the results from video 1 (and the old version of the app and the excel, which are all consistent).

Let me know if I can test anything else - I've been trying to pinpoint what is causing this for a few hours but I can't understand why this specific set of operations would lead to a different result.

**Comment by zross** [comment]
@ktrzcinskiwb I'm looking into this. If you could please give me a textual step by step so that I can reproduce the two scenarios. I'm finding it hard to reproduce what you have in the video. Also, which of the values is correct 28.4 or 28.3.

**Comment by ktrzcinskiwb** [comment]
@zross

the correct value is 28.3% 

to reproduce the error you need to 
1. switch "Alimentacao" to "isencao total" 
2. but then for the categories "cerveja", "outras bebidas alcoolicas" and "refigerantes" (the three categories that already have imposto seletivo in the baseline) restore imposto seletivo
3. for "alimentacao fora de domicilio" put aliquota padrao
4. then for each macro categegory use the newly added buttons to switch all cashback to 0

IMPORTANT: I just noted that we have a regular category called "Recreações culturais e esportivas" and a big macro-category with the same name. Could this be creating the conflict?

**Comment by zross** [comment]
The `Recreações culturais e esportivas` thing is a new issue #101. I'll respond there.

**Comment by ktrzcinskiwb** [comment]
@zross - 
this may also be causing the difference in results we are getting, because it only happens when I make these steps in this order

**Comment by zross** [comment]
A new version is deployed, could you please see if that fixed the issue?

**Comment by ktrzcinskiwb** [comment]
Yes I will check asap, thank you
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ktrzcinskiwb** [comment]
@zross 

The error is fixed, thank you! Now I'm have another minor problem - the macro button in the "Demais" category is not working, though I think everything else is working perfectly.


https://github.com/worldbank/simvat/assets/164540200/140d50da-c7e2-44cb-8d40-5af9bec4cfc6
