### ISSUE TITLE
Add attribution?

### ISSUE THREAD

**Issue by zross** [worldbank/simvat#102]
@ktrzcinskiwb @glaraiba any chance we could add a reference to my business somewhere, perhaps in the about section? Like "Application created by [ZevRoss Spatial Analysis](www.zevross.com)". I understand if that's not possible.

**Comment by ktrzcinskiwb** [comment]
@zross 

Yes happy to include it! Please put "O aplicativo foi criado por ZevRoss Spatial Analysis" at the end of the first paragraph on the em geral page - so at the end of this text here:
![image](https://github.com/worldbank/simvat/assets/164540200/e8d3c870-4931-47be-8fdf-8da8ca0029ec)

**Comment by zross** [comment]
great thanks, I've added it.
