### ISSUE TITLE
Additional figures

### ISSUE THREAD

**Issue by ktrzcinskiwb** [worldbank/simvat#103]
@zross 

We are still working out the exact details of the other extensions for the App, but one thing that is already set are the additional graphs. As we discussed, we think this would work best as three tabs, because the graphs are very similar. I would put on the titles of the tabs as the labels on the Y axis of the graphs "Proporção de renda" - " "Proporção de consumo" - "Proporção das receitas"

And then the titles on the actual graph would be 
"Carga tributária como proporção da renda por decil (%)"
"Carga tributária como proporção do consumo por decil (%)"
"Carga tributária como proporção das receitas por decil (%)"

In a moment I will share on OneDrive a new file SimVAT_3.1.4, a couple notes on this:
- There are some simple additional calculation in the DIST sheet (columns H-L) - they use existing data, just decile aggregates and division. I don't know if you want to import the whole new file, or simply generate the new figures. The results (and underlying calculations) have not changed for now. 
- I haven't yet brought in the flexible legend that you have in the web application, of course please keep these for all the graphs (PLP 68, minha simulacao, Alíquota padrão única).
- since we are no longer showing the regional graph, I have replaced the variable "UF" (state) with missing values. This preserves the structure of the data, but makes the file much lighter. Just in case you take not that there are far fewer observations, this is intentional. 

As always, if anything is not running smoothly just let me know so you don't waste your own time

**Comment by zross** [comment]
I put a first pass here: https://spatial.shinyapps.io/worldbank-simvat-dev/

**Comment by ktrzcinskiwb** [comment]
@zross 

Thanks again for the graphs, they look just as I imagined.

I asked a native POR speaking colleague and I would like to ask you to please change:
Proporção de renda --> Proporção da renda
Proporção de consumo --> Proporção do consumo (in the tab and on the y-axis of the graph)

And the title of the third graph:
Carga tributária como proporção do consumo por decil (%) --> Participação na receita total por decil (%)

**Comment by zross** [comment]
I like how you give me the exact letters of what I have now and what you want changed. It makes it easy to search and replace.

There are several other places where we have "de renda" or "de consumo", I assume this is OK in other places?

**Comment by ktrzcinskiwb** [comment]
The rest of the text has been proof-read so I will not assume to make any changes there, let's leave all else as is, thanks Zev.

**Comment by zross** [comment]
I have not deployed this yet, I will do that once we have a few more things checked off.
