### ISSUE TITLE
Adding a link to the imposto seltivo

### ISSUE THREAD

**Issue by ktrzcinskiwb** [worldbank/simvat#104]
@zross 

we would like to add a link to the title of the Imposto Seletivo with some additional information - we imagined the easiest way to do this would be to add a that opens the hipoteses_e_limitacoes PDF to page 3. The idea is that the actual text that reads “Imposto seletivo” (as in the mockup image below) is a hyperlink, so that when the user clicks, it would provide the additional information. 

![image](https://github.com/worldbank/simvat/assets/164540200/399c307f-7317-4d50-8c30-226cce4fa934)

this would require:

- [x] updating the hipoteses_e_limitacoes document with the attached (including in the Sobre a ferramenta page)
- [x] adding a link to page 3 which starts with "Imposto seletivo" to the column title in the table
[Hipóteses_e_limitações.pdf](https://github.com/user-attachments/files/15514165/Hipoteses_e_limitacoes.pdf)

**Comment by zross** [comment]
Is the PDF page 3 supposed to start with "Imposto seletivo"? Here is what I see

<img width="592" alt="image" src="https://github.com/worldbank/simvat/assets/1395177/603013cc-2643-4a2e-90cc-618e0473ea84">

**Comment by ktrzcinskiwb** [comment]
Yes, the PDF didn't overwrite, thank you for catching this: 
[Hipóteses_e_limitações.pdf](https://github.com/user-attachments/files/15515446/Hipoteses_e_limitacoes.pdf)

**Comment by zross** [comment]
I've posted a version at: https://spatial.shinyapps.io/worldbank-simvat-dev/

I'm finding that the link directly to page 3 is not 100% consistent, see what you find.

**Comment by ktrzcinskiwb** [comment]
Thanks for this Zev - it seems to be working well on my end, but I will keep testing as we go.

**Comment by zross** [comment]
Done for now? (You can leave open)
