### ISSUE TITLE
Files for Excel list and test video

### ISSUE THREAD

**Issue by ktrzcinskiwb** [worldbank/simvat#37]
The Excel file with the lists:
[Categorias.csv](https://github.com/zevross/rpkg-worldbank-simvat/files/15275192/Categorias.csv)

And the video:
https://github.com/zevross/rpkg-worldbank-simvat/assets/164540200/c8624ec4-7421-4972-b56b-8f3cf2467248

And the link to VidCast:
https://app.vidcast.io/share/03fc7089-9ae4-41a0-a9df-55f7d39f8913

And the embed code:
<div style="padding-bottom:56.25%; position:relative; display:block; width: 100%">
                <iframe src=https://app.vidcast.io/share/embed/03fc7089-9ae4-41a0-a9df-55f7d39f8913 width="100%" height="100%" title="video1_v1" frameborder="0" loading="lazy" allowfullscreen style="position:absolute; top:0; left: 0;border: solid; border-radius:12px;"></iframe>
</div>

**Comment by zross** [comment]
This is in the main URL
