### ISSUE TITLE
Add a warning that changing the base will reset the simulation parameters

### ISSUE THREAD

**Issue by ktrzcinskiwb** [worldbank/simvat#81]
@zross

Would it be possible to please add a warning in red that when they change the base it will overwrite their parameters? This could be simple text under the title 
![image](https://github.com/zevross/rpkg-worldbank-simvat/assets/164540200/cf147550-29ea-440a-ab8a-d3f87742ba2d)

Or a little warning symbol like you have under the missing cells that works like the info box:
![image](https://github.com/zevross/rpkg-worldbank-simvat/assets/164540200/1a746238-804b-4401-9283-bdd359cae93c)

In the Excel we had the reset button so this wasnt an issue, but it can be confusing for the user why they are losing their simulations each time

The text in POR would be:
"Atenção: quando você altera seu cenário de base, sua simulação será resetada."

**Comment by zross** [comment]
This is in the main URL
